### PR TITLE
Dependency updated

### LINKED ISSUE #53: Installation by composer fails at the moment
Tried to install this through composer instead of a clone and it failed, seems to be because it can't find the phpasn1 commit

@aztech-dev 
```
  Problem 1
    - Installation request for mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master].
    - mdanter/ecc dev-master requires fgrosse/phpasn1 dev-master#1033ca99966ee75b957d6f923dc21f4dad9b334b -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

### PR DESCRIPTION
**Pull request by Spomky**
* The library now uses PHPASN1 `v1.0.*`

Should fix #53 

Other minor modifications:
* Badges added
* Code design using PHP-CS-FIXER

### CODE REVIEW

**Comment by aztech-dev** [comment]
Which ruleset are you using with phpcbf ?

**Comment by Spomky** [comment]
vendor/bin/phpcbf --standard=phpcs.xml -n src

**Comment by aztech-dev** [comment]
Ok :) I think the rules need updating, some of them are missed...

**Comment by aztech-dev** [comment]
And while you're at it, could you remove humbug/humbug from the dev dependencies please ? It's causing more composer install issues (I know it's my fault, but that way it'll get fixed faster)

**Comment by Spomky** [comment]
Done

**Comment by aztech-dev** [comment]
Thanks :)

**Comment by btcdrak** [comment]
@Spomky Thanks for the PR. In future please can you separate CS commits from other stuff.

**Pull request merged**
