### PR TITLE
Ecmath

### PR DESCRIPTION
**Pull request by afk11**
Added an EcMath class, which accepts a numeric value or a PointInterface.
Added an interface, covering add(), mul(), getDouble(), mod(), and cmp(), and result(). 

There are tests for the EcMath class, mainly just asserting some operations like (k+k)*G = (k*G)+(k*G). 
Test.php has some examples of usage. (Private/Public classes are not the classes used in this library)

The library tolerates you trying to add an integer to a point, by carrying out the point multiplication when required. 
It will throw an exception if you try to do something impossible, like multiplying two points together.

I haven't added an equals() function, like the Point and Math class both have, though I will probably add this shortly.  Also want to refactor the Math, EcMath, and Crypto components into namespaces, after we discuss it.

### CODE REVIEW

**Comment by btcdrak** [comment]
What is the status of this PR?

**Comment by afk11** [comment]
I'll commit something in a sec to address the Point method changes and the test cases, that should be it then?

**Comment by btcdrak** [comment]
should be

**Comment by afk11** [comment]
Just going over this once more, removing the sign2() function in PrivateKey

**Comment by aztech-dev** [comment]
Looks good :)

**Comment by btcdrak** [comment]
ACK

**Pull request merged**
