### PR TITLE
Tests changes

### PR DESCRIPTION
**Pull request by Spomky**
* Tests on PHP 7 added
* Code coverage is now sent only if tests succeded

### CODE REVIEW

**Comment by aztech-dev** [comment]
ACK

**Comment by btcdrak** [comment]
Looks like upstream library needs to be made PHP 7 safe, until then this PR cannot be merged

`FG\ASN1\Universal\Null`

**Comment by afk11** [comment]
ACK

**Comment by btcdrak** [comment]
Cant merge until the upstream library has been made PHP7 safe.

**Comment by afk11** [comment]
ping @Spomky, looks like your changes were merged in ASN1

**Comment by btcdrak** [comment]
Would need to update the `composer.json` to take those changes into account. Have they tagged it yet?

**Comment by afk11** [comment]
Yup, since merging they've tagged 1.3.1

**Comment by btcdrak** [comment]
Great so let's get the `composer.json` updated to `1.3.*`

**Comment by Spomky** [comment]
Great. 

I will update my PR on Monday.
Stay tuned.

**Comment by btcdrak** [comment]
ACK

**Comment by Spomky** [comment]
Thanks

**Pull request merged**
