### PR TITLE
Refactor priv/pub key generation & message signing

### PR DESCRIPTION
**Pull request by aztech-dev**
This is mostly to simplify private/public key generation and also prepare for #29

As usual, this is a nice BC break.

And sorry, I forgot to do two separate commits, so there's some whitespace changes mixed in with the refactoring.

### CODE REVIEW

**Comment by aztech-dev** [comment]
ping @btcdrak @afk11 @rubensayshi Any comments on P/R ?

**Comment by rubensayshi** [comment]
looks good imo!

I haven't spend enough time with that code to really be able to give good feedback on it though ...

**Comment by aztech-dev** [comment]
Allright, thx for the feedback... I'll wait for the others' feedback

**Comment by btcdrak** [comment]
What is the BC break?

**Comment by aztech-dev** [comment]
PrivateKeyInterface:
  - `sign()` method is removed (message signing is moved to Signature namespace)

PrivateKey:
  - constructor method signature is changed (argument ordering)

PublicKeyInterface:
  - `verifies` method is removed (moved to Signature NS)
  - `getPrivateKey()` method is removed. It did not feel logical there (you need a GeneratorPoint to get a public key, and to get a private key, you need the secret, so might as well generate PrivateKey straight from the generator -- it's more straightforward)

PublicKey
  - constructor method signature is changed (argument ordering)

I think that's about it.

**Comment by aztech-dev** [comment]
Ping again ? :D @btcdrak @afk11

**Comment by btcdrak** [comment]
I am waiting on @afk11 to reply.

**Comment by aztech-dev** [comment]
Ok, thanks.

**Comment by afk11** [comment]
This looks good, sorry I missed the notifications on this lately. Yeah the changes are all sound, I know I was surprised initially when I saw the getPrivateKey and getPublicKey functions way down the bottom of GeneratorPoint in there. Should make it easier for others to get started.

The only other thing I can think of in terms of cleaning up is GeneratorPoint->mul() happens to produce a GgeneratorPoint if you're willing to change it? I can open an issue and discuss later either, but since it's a cleanup...

**Comment by aztech-dev** [comment]
You mean return a Point instead of a GeneratorPoint ?

**Comment by afk11** [comment]
Ah yes, I meant to return a Point instead of GeneratorPoint.

**Comment by aztech-dev** [comment]
Ok, then might as well do the same for getDouble and add, no ? I'll update the P/R

**Comment by aztech-dev** [comment]
Done, I pushed the cleanup a bit further by adding a factory method to curves and deriving GeneratorPoint from Point instead of composing, since we're returning Points and not GeneratorPoints from add/getDouble/mul, composition was just pointless.

**Comment by btcdrak** [comment]
Tests are failing

**Comment by aztech-dev** [comment]
Yup, investigating, they were passing locally, and honestly, all I did afterwards was run the PHPCS fixer... kindda clueless as to what happened.

**Comment by aztech-dev** [comment]
Allright, fixed.

**Comment by btcdrak** [comment]
Needs rebase.

**Comment by aztech-dev** [comment]
Done, waiting for tests.

**Comment by aztech-dev** [comment]
All good !

**Pull request merged**
