### PR TITLE
Call EcDH::calculateSharedKey in PrivateKey::createExchange()

### PR DESCRIPTION
**Pull request by afk11**
Fix readme, by EcDH::calculateSharedKey() in PrivateKey::createExchange()

### CODE REVIEW

**Comment by aztech-dev** [comment]
Why not do it in EcDH::encrypt / decrypt methods instead ? It'd prevent any possible misuse

**Comment by btcdrak** [comment]
What's the status of this PR?

**Comment by aztech-dev** [comment]
ACK from me -- any improvement is better than none :)

**Comment by afk11** [comment]
I did mean to follow your suggestion on doing it in encrypt() / decrypt(). Wiped my working dir with that branch, I'll resubmit :)

**Comment by afk11** [comment]
Went with @aztech-dev's idea on this,  submitted in #82

**Pull request closed without merging**
